export const endpoints = {
  scenarios_stats: "/scenarios/statistics",
  scenarios: "/scenarios",
  updateScenario: (id) => `/scenario/${id}`,
  getScenarioById: (id) => `/scenario/${id}`,
  profiles: "/profiles",
  profileUpdate: (id) => `/profile/${id}`,
  profileDelete: (id) => `/profile/${id}`,
  profileById: (id) => `/profile/${id}`,
  tags: "/tags",
  platforms: "/platforms",
  frame_urls: "/frame_urls",
  blacklist_urls: "/blacklist_urls",
  profiles_thumbnails: "/profiles/thumbnails",
  search_engines: "/search_engines",
  proxies: "/proxies",
  proxieDelete: (id) => `/proxy/${id}`,
  scenarioEnable: (id) => `/scenario/${id}/enable`,
  scenarioDisable: (id) => `/scenario/${id}/disable`,
};
